services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
  app_sort:
    container_name: app_sort
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pg:
